import time
import requests

start_time = time.time()
requests.get('https://www.google.ru/')
end_time = time.time()
print(end_time - start_time)
start_time = time.time()
requests.get('https://yad2.co.il/')
end_time = time.time()
print(end_time - start_time)
start_time = time.time()
requests.get('https://www.google.ru/')
end_time = time.time()
print(end_time - start_time)
start_time = time.time()
requests.get('https://www.google.ru/')
end_time = time.time()
print(end_time - start_time)
start_time = time.time()
requests.get('https://yad2.co.il/')
end_time = time.time()
print(end_time - start_time)
start_time = time.time()
requests.get('https://www.google.ru/')
end_time = time.time()
print(end_time - start_time)