let x = require('./operators.js')
let path = require('path')
let filename = path.basename('C:/Users/den-s/OneDrive/Desktop/DI-bootcamp/week10/day1/calculator.js')
console.log(filename)
console.log(x.add(1,3))
console.log(x.div(1,3))