# Generated by Django 4.2.2 on 2023-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_share', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
