-- create table students
-- (
-- 	id serial primary key,
-- 	last_name char(30),
-- 	first_name char(30),
-- 	birth_date date
-- )

-- insert into students(first_name,last_name,birth_date)
-- values
-- ('Marc','Benichou','02-11-1998'),
-- ('Yoan','Cohen','03-12-2010'),
-- ('Lea','Benichou','27-07-1987'),
-- ('Amelia','Dux','07-04-1996'),
-- ('David','Grez','14-06-2003'),
-- ('Omer','Simpson','03-10-1980')
-- select * from students
-- select * from students where last_name = 'Benichou' and first_name = 'Marc'
-- select * from students where last_name = 'Benichou' or first_name = 'Marc'
-- select * from students where first_name like '%a%'
-- alter table students
-- alter column first_name type text
-- alter column last_name type text
-- It didn't work because i made it char(30) and last latter was empty space ))
-- select * from students where first_name like '%a'
-- select * from students where first_name like 'a%'
-- select * from students where first_name like '%a_'
-- select * from students where id between 1 and 3
-- select * from students where birth_date > '01-01-2000'