# Generated by Django 4.2.1 on 2023-06-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
