# Generated by Django 4.2.1 on 2023-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_rate',
            name='daily_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
